const teamData = [
  {
    id: 1,
    slug: "aaqib-nazir",
    name: "Aaqib Nazir",
    designation: "Director - Engg. and Technical Operations",
    email: "aaqib.nazir@nayaabengineering.com",
    phone: "+91 194 220 1145",
    image: "/assets/team/aqib.png",
    linkedin: "https://linkedin.com/in/aaqib-nazir",
    bio: "Aaqib leads Nayaab Engineering Innovations with a focus on sustainable infrastructure and long-term client partnerships across South Asia.",
    experience: "22+ Years",
    department: "Executive Leadership",
  },
  {
    id: 2,
    slug: "junaid-bilal",
    name: "Junaid Bilal",
    designation: "Architect",
    email: "junaid@nayaabengineering.com",
    phone: "+91 194 220 1146",
    image: "/assets/team/farah-wani.jpg",
    linkedin: "https://linkedin.com/in/farah-bashir-wani",
    bio: "Farah drives the technology roadmap, overseeing automation systems and digital transformation initiatives across all engineering divisions.",
    experience: "18+ Years",
    department: "Technology & Innovation",
  },
  {
    id: 3,
    slug: "sajid",
    name: "Sajid",
    designation: "Head of Structural Engineering",
    email: "sajid@nayaabengineering.com",
    phone: "+91 194 220 1147",
    image: "/assets/team/imran-baba.jpg",
    linkedin: "https://linkedin.com/in/imran-showkat-baba",
    bio: "Imran brings deep expertise in structural design and seismic-resilient engineering for large-scale industrial and commercial projects.",
    experience: "16+ Years",
    department: "Structural Engineering",
  },
  {
    id: 4,
    slug: "sana-mushtaq-dar",
    name: "Sana Mushtaq Dar",
    designation: "Director of Operations",
    email: "sana.dar@nayaabengineering.com",
    phone: "+91 194 220 1148",
    image: "/assets/team/sana-dar.jpg",
    linkedin: "https://linkedin.com/in/sana-mushtaq-dar",
    bio: "Sana ensures operational excellence across project sites, managing quality control, safety compliance, and resource planning.",
    experience: "14+ Years",
    department: "Operations",
  },
  {
    id: 5,
    slug: "tariq-ahmad-lone",
    name: "Tariq Ahmad Lone",
    designation: "Head of Electrical Systems",
    email: "tariq.lone@nayaabengineering.com",
    phone: "+91 194 220 1149",
    image: "/assets/team/tariq-lone.jpg",
    linkedin: "https://linkedin.com/in/tariq-ahmad-lone",
    bio: "Tariq leads the electrical systems division, specializing in power distribution, automation, and industrial control architecture.",
    experience: "19+ Years",
    department: "Electrical Engineering",
  },
];

export default teamData;
